import {
  PROJECT_DIR,
  PR_TARGET_BRANCH,
  MERGE_ADMIN_ID,
  MERGE_DEV_BRANCH,
  MERGE_PROD_BRANCH,
  lastDevMerge,
  MAX_ACTIVE_CHATS,
  USER_GITHUB_MAP,
} from "./config.mjs";
import { t } from "./i18n.mjs";
import { getChatKey, shell } from "./utils.mjs";
import { activeSessions, activeRequests, getOrCreateSession, destroySession } from "./session.mjs";
import { pushBranch, createPR } from "./worktree.mjs";
import { generatePrSummary } from "./claude.mjs";

export function registerCommands(bot) {
  // /start
  bot.command("start", async (ctx) => {
    await ctx.reply(`👋 ${t("start_hello")}`);
  });

  // /new
  bot.command("new", async (ctx) => {
    const chatKey = getChatKey(ctx);
    const userId = ctx.from.id;

    if (activeSessions.has(chatKey)) {
      const old = destroySession(chatKey);
      if (old) {
        try { shell(`git branch -D "${old.branchName}"`, PROJECT_DIR); } catch {}
        await ctx.reply(
          `🗑 ${t("old_session_deleted", old.branchName)}`,
          { parse_mode: "HTML" }
        );
      }
    }

    if (activeSessions.size >= MAX_ACTIVE_CHATS) {
      await ctx.reply(`⛔ ${t("chat_limit_full", MAX_ACTIVE_CHATS)}`);
      return;
    }

    try {
      const session = getOrCreateSession(chatKey, userId);
      if (!session) {
        await ctx.reply(`⛔ ${t("chat_limit_reached", MAX_ACTIVE_CHATS)}`);
        return;
      }

      await ctx.reply(
        `✅ ${t("new_session_created", session.branchName, session.worktreePath, PR_TARGET_BRANCH)}`,
        { parse_mode: "HTML" }
      );
    } catch (err) {
      console.error("Error creating session:", err.message);
      await ctx.reply(`❌ ${t("session_create_failed", err.message.slice(0, 200))}`);
    }
  });

  // /done
  bot.command("done", async (ctx) => {
    const chatKey = getChatKey(ctx);
    const session = activeSessions.get(chatKey);

    if (!session) {
      await ctx.reply(`ℹ️ ${t("no_active_session")}`);
      return;
    }

    await ctx.replyWithChatAction("typing");

    try {
      let hasCommits = false;
      try {
        const log = shell(
          `git log "origin/${PR_TARGET_BRANCH}..HEAD" --oneline`,
          session.worktreePath
        );
        hasCommits = log.length > 0;
      } catch {
        hasCommits = false;
      }

      if (!hasCommits) {
        await ctx.reply(`⚠️ ${t("no_commits")}`);
        return;
      }

      await ctx.reply(`📤 ${t("pushing_branch")}`);
      pushBranch(session.branchName, session.worktreePath);

      const commitLog = shell(
        `git log "origin/${PR_TARGET_BRANCH}..HEAD" --pretty=format:"- %s"`,
        session.worktreePath
      );

      const ghUser = USER_GITHUB_MAP.get(ctx.from.id);
      const coAuthors = [];
      for (const [tgId, ghUsername] of USER_GITHUB_MAP) {
        if (tgId !== ctx.from.id) {
          coAuthors.push(`Co-authored-by: ${ghUsername}`);
        }
      }

      await ctx.reply(`🧠 ${t("generating_pr")}`);
      const summary = generatePrSummary(session, commitLog);

      const prTitle = summary?.title
        ? `[BugBot] ${summary.title}`
        : `[BugBot] ${session.branchName}`;
      const prBody =
        (summary?.body ? `## Summary\n${summary.body}\n\n` : "") +
        `## Commits\n${commitLog}\n\n` +
        `## Details\n- Branch: \`${session.branchName}\`\n` +
        `- Requested by: ${ghUser || ctx.from.id}\n` +
        (coAuthors.length > 0 ? `\n${coAuthors.join("\n")}` : "") +
        `\n\n🤖 Generated by BugBot (Claude Code)`;

      await ctx.reply(`📋 ${t("creating_pr")}`);
      const prUrl = createPR(session.branchName, prTitle, prBody, ctx.from.id);

      destroySession(chatKey);

      await ctx.reply(
        `✅ ${t("done_success", prUrl, session.branchName, PR_TARGET_BRANCH)}`,
        { parse_mode: "HTML" }
      );
    } catch (err) {
      console.error("Error in /done:", err.message);
      await ctx.reply(`❌ ${t("error_generic", err.message.slice(0, 300))}`);
    }
  });

  // /status
  bot.command("status", async (ctx) => {
    const chatKey = getChatKey(ctx);
    const session = activeSessions.get(chatKey);

    if (!session) {
      await ctx.reply(`ℹ️ ${t("no_active_session")}`);
      return;
    }

    let commitCount = "?";
    try {
      commitCount = shell(
        `git rev-list --count "origin/${PR_TARGET_BRANCH}..HEAD"`,
        session.worktreePath
      );
    } catch {}

    const age = Math.round((Date.now() - session.createdAt) / 60000);
    const ghUser = USER_GITHUB_MAP.get(session.userId);
    const sessionIdStr = session.sessionId ? session.sessionId.slice(0, 8) + "..." : "—";

    await ctx.reply(
      `📊 ${t("status_info",
        session.branchName,
        session.worktreePath,
        ghUser || session.userId,
        commitCount,
        age,
        sessionIdStr,
        session.messageCount,
        Math.round(session.totalChars / 1000),
        activeSessions.size,
        MAX_ACTIVE_CHATS
      )}`,
      { parse_mode: "HTML" }
    );
  });

  // /sessions
  bot.command("sessions", async (ctx) => {
    if (activeSessions.size === 0) {
      await ctx.reply(`ℹ️ ${t("no_sessions", MAX_ACTIVE_CHATS)}`);
      return;
    }

    let msg = `📋 ${t("sessions_header", activeSessions.size, MAX_ACTIVE_CHATS)}`;

    for (const [, s] of activeSessions) {
      const age = Math.round((Date.now() - s.createdAt) / 60000);
      const ghUser = USER_GITHUB_MAP.get(s.userId) || s.userId;
      msg += `• <code>${s.branchName}</code> — ${ghUser}, ${age} min\n`;
    }

    await ctx.reply(msg, { parse_mode: "HTML" });
  });

  // /drop
  bot.command("drop", async (ctx) => {
    const chatKey = getChatKey(ctx);
    const session = destroySession(chatKey);

    if (!session) {
      await ctx.reply(`ℹ️ ${t("no_session_to_drop")}`);
      return;
    }

    try {
      shell(`git branch -D "${session.branchName}"`, PROJECT_DIR);
    } catch {}

    await ctx.reply(
      `🗑 ${t("session_dropped", session.branchName)}`,
      { parse_mode: "HTML" }
    );
  });

  // /stop
  bot.command("stop", async (ctx) => {
    const chatKey = getChatKey(ctx);
    const session = activeSessions.get(chatKey);

    if (!session || !activeRequests.has(chatKey)) {
      await ctx.reply(`ℹ️ ${t("nothing_to_stop")}`);
      return;
    }

    if (session.activeProc) {
      try { session.activeProc.kill("SIGTERM"); } catch {}
      session.activeProc = null;
    }
    activeRequests.delete(chatKey);

    await ctx.reply(`🛑 ${t("stopped")}`);
  });

  // /id
  bot.command("id", async (ctx) => {
    const ghUser = USER_GITHUB_MAP.get(ctx.from.id);
    await ctx.reply(
      `🆔 ${t("id_info", ctx.from.id, ghUser)}`,
      { parse_mode: "HTML" }
    );
  });

  // /merge_dev
  bot.command("merge_dev", async (ctx) => {
    if (ctx.from.id !== MERGE_ADMIN_ID) {
      await ctx.reply(`⛔ ${t("admin_only")}`);
      return;
    }

    await ctx.reply(`🔀 ${t("merging_dev", PR_TARGET_BRANCH, MERGE_DEV_BRANCH)}`);
    await ctx.replyWithChatAction("typing");

    lastDevMerge.status = "running";
    lastDevMerge.timestamp = Date.now();
    lastDevMerge.triggeredBy = ctx.from.id;

    try {
      shell(`git fetch origin`, PROJECT_DIR);
      shell(`git checkout "${MERGE_DEV_BRANCH}"`, PROJECT_DIR);
      shell(`git pull origin "${MERGE_DEV_BRANCH}"`, PROJECT_DIR);
      shell(`git merge "origin/${PR_TARGET_BRANCH}"`, PROJECT_DIR);
      shell(`git push origin "${MERGE_DEV_BRANCH}"`, PROJECT_DIR);

      lastDevMerge.status = "success";
      lastDevMerge.timestamp = Date.now();
      await ctx.reply(`✅ ${t("merge_dev_ok", PR_TARGET_BRANCH, MERGE_DEV_BRANCH)}`);
    } catch (err) {
      console.error("Merge dev failed:", err.message);
      lastDevMerge.status = "failed";
      lastDevMerge.timestamp = Date.now();
      try { shell(`git merge --abort`, PROJECT_DIR); } catch {}
      await ctx.reply(`❌ ${t("merge_dev_failed", err.message.slice(0, 300))}`);
    } finally {
      try { shell(`git checkout "${PR_TARGET_BRANCH}"`, PROJECT_DIR); } catch {}
    }
  });

  // /merge_prod
  bot.command("merge_prod", async (ctx) => {
    if (ctx.from.id !== MERGE_ADMIN_ID) {
      await ctx.reply(`⛔ ${t("admin_only")}`);
      return;
    }

    if (lastDevMerge.status !== "success") {
      let reason = t("merge_prod_blocked_none");
      if (lastDevMerge.status === "failed") {
        reason = t("merge_prod_blocked_failed");
      } else if (lastDevMerge.status === "running") {
        reason = t("merge_prod_blocked_running");
      }
      await ctx.reply(`⛔ ${t("merge_prod_blocked", reason)}`);
      return;
    }

    await ctx.reply(`🔀 ${t("merging_prod", MERGE_DEV_BRANCH, MERGE_PROD_BRANCH)}`);
    await ctx.replyWithChatAction("typing");

    try {
      shell(`git fetch origin`, PROJECT_DIR);
      shell(`git checkout "${MERGE_PROD_BRANCH}"`, PROJECT_DIR);
      shell(`git pull origin "${MERGE_PROD_BRANCH}"`, PROJECT_DIR);
      shell(`git merge "origin/${MERGE_DEV_BRANCH}"`, PROJECT_DIR);
      shell(`git push origin "${MERGE_PROD_BRANCH}"`, PROJECT_DIR);

      await ctx.reply(`✅ ${t("merge_prod_ok", MERGE_DEV_BRANCH, MERGE_PROD_BRANCH)}`);
    } catch (err) {
      console.error("Merge prod failed:", err.message);
      try { shell(`git merge --abort`, PROJECT_DIR); } catch {}
      await ctx.reply(`❌ ${t("merge_prod_failed", err.message.slice(0, 300))}`);
    } finally {
      try { shell(`git checkout "${PR_TARGET_BRANCH}"`, PROJECT_DIR); } catch {}
    }
  });
}
